### ISSUE TITLE
如何扩展自己的 UI 和注入 物料包？

### ISSUE THREAD

**Issue by StringKe** [ByteCrazy/chameleon#1]
我看 UI 和 阿里的那个相似，功能上呢？

**Comment by hlerenow** [comment]
## lowcode 区别

- 和 lowcode 的理念基本一样，但是  chameleon 的架构更精简，代码耦合度更低，lowcode 内部耦合了阿里内部的一些项目逻辑。
- lowcode 的基础功能，chamelon 会逐渐支持；现在已经支持的：大纲树，拖拽编辑，循环渲染，导出 schema，自定义物料，插件 以及基于 schema 渲染等等
- 所有模块都可以被替换，不存在必须要使用内置的功能模块的情况。如大纲树，渲染器，右侧面板，在符合引擎的插件规则下都可以被二次开发整个替换。
- 二次开发的定制自由度更高
- 引擎底层支持 state 数据模型，修改数据后, UI 自动响应，对应的 UI 界面也可支持 二次自定义开发。
- chamelon schema 协议和 lowcode 协议不完全一致，整体结构一致。
- 支持 react-18

## 如何扩展自己的 UI 和注入 物料包

目前引擎层面也已经支持，对应的开发文档还没有时间编写， 不过可以参考 [demo](https://github.com/ByteCrazy/chameleon-demo/blob/main/src/page/Editor/index.tsx) 项目。后续会搭建 基础的使用文档和二次开发文档站点。

**Comment by StringKe** [comment]
https://github.com/ByteCrazy/chameleon/blob/085f0ba25586ba34cb3525edab488f30cd1ed790/packages/engine/src/component/MonacoEditor/index.tsx#L2-L3

这里的编辑器是否可以替换成 https://www.npmjs.com/package/@monaco-editor/react 

amis 和 lowcode 都存在这个问题，这个包需要额外的 webpack 才可以进行正确的打包，另外在 nextjs 中 monaco-editor 内导入了全局 css 这在 nextjs 中是不被允许的。

**Comment by hlerenow** [comment]
暂时不会替换：
1. monaco-editor 构建的确需要额外的 webpack 或者 vite 配置，核心原因是因为 webwroker 需要单独打包配置，如果不配置也能运行，就是编辑器没有语法提示，会有一个 js load error，后续会问文档提及这块注意事项。
2. [@monaco-editor/react](https://www.npmjs.com/package/@monaco-editor/react) 这个包不用配置的是因为直接引用了第三方的 cdn 地址。
3. 在 nextjs 场景下应该将 chameloen 组件配置为只在客户端渲染，否则 ssr 会出异常，因为涉及客户端dom操作。

**Comment by StringKe** [comment]
monaco-editor 里导入了全局 css ，nextjs 中不允许这样的操作，我已经将 chameloen 配置成 客户端渲染了，使用 NoSSR component 和 dynamic 导入 都是一样的错误。

**Comment by hlerenow** [comment]
目前没有适配 ssr 相关的渲染，也没有适配 nextjs 框架，目前只适合 spa 模式 的 csr 渲染，这里先标记为 enhancement,  后续计monaco-editor 独立出来，从外部传入

**Comment by StringKe** [comment]
> 

期待这个特性，目前受 monaco-editor 影响比较严重，在 [nx.dev](https://nx.dev) 提供的 @nrwl/react 方案中 monaco-editor 的 webpack-plugin 也有配合上的问题。

**Comment by StringKe** [comment]
@hlerenow 大佬有联系方式么，可以咨询一些关于 chameleon 的问题么？

**Comment by hlerenow** [comment]
你直接提 issue 吧，看见了我都会回复。

**Comment by hlerenow** [comment]
文档：https://hlerenow.github.io/chameleon/documents/docs/tutorial/addCustomComponent

**Comment by hlerenow** [comment]
已经使用 @monaco-editor/react 替换 monaco-editor
@StringKe
