### ISSUE TITLE
Bug: 部分组件在画布中均无法选中以显示操作辅助区

### ISSUE THREAD

**Issue by KurumiRin** [ByteCrazy/chameleon#4]
如demo中的button和audio组件，其组件外层非div元素，拖入画布中无法选中该组件以展示操作辅助。

**Comment by hlerenow** [comment]
https://github.com/hlerenow/chameleon 可以去这里提 iuess

1. Button 是物料配置为不能选中，用于测试的
2. audio 本身是不会渲染的，因为没开启 展示控制面板, 是 html 的行为，右侧面板打开后就可以被选中
